// <auto-generated />
namespace Tamirci.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Kategori_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Kategori_added));
        
        string IMigrationMetadata.Id
        {
            get { return "202211231923085_Kategori_added."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
