// <auto-generated />
namespace Tamirci.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class İL_İLÇE_KATEGORİ_İSDELETED_ADDED : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(İL_İLÇE_KATEGORİ_İSDELETED_ADDED));
        
        string IMigrationMetadata.Id
        {
            get { return "202212070628544_İL_İLÇE_KATEGORİ_İSDELETED_ADDED"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
