// <auto-generated />
namespace Tamirci.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Mesalar_acyive_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mesalar_acyive_added));
        
        string IMigrationMetadata.Id
        {
            get { return "202212280841064_Mesalar_acyive_added."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
