// <auto-generated />
namespace Tamirci.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class puan_tamirci_relations_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(puan_tamirci_relations_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "202211272145151_puan_tamirci_relations_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
