// <auto-generated />
namespace Tamirci.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class il_ilçe_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(il_ilçe_added));
        
        string IMigrationMetadata.Id
        {
            get { return "202211280554165_il_ilçe_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
