// <auto-generated />
namespace Tamirci.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class rating_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rating_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "202212062048283_rating_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
